model_params:
  cell_embedding_dim: 1280
  output_dim: 1280
  condition_dim: 256
  hidden_dims: [2560, 1280, 1280]

train_params:
  num_epochs: 3
  batch_size: 128

dataset_params:
  sciplex_adata_path: "C:\\Users\\curea\\Documents\\bioFM for drug discovery\\dege-fm\\data\\sciplex\\sciplex_preprocessed.h5ad"
  zhao_adata_path: "C:\\Users\\curea\\Documents\\bioFM for drug discovery\\dege-fm\\data\\zhao\\zhao_preprocessed.h5ad"
  seed: 1702
