model_params:
  cell_embedding_dim: 1280
  output_dim: 1280
  condition_dim: 256
  hidden_dims: [2560, 1280, 1280]

train_params:
  num_epochs: 1
  batch_size: 128
  lr: 0.0001

dataset_params:
  sciplex_adata_path: "/home/victor/projects/dege-fm/data/sciplex/sciplex_preprocessed.h5ad"
  zhao_adata_path: "/home/victor/projects/dege-fm/data/zhao/zhao_preprocessed.h5ad"
  sciplex_drugs_train: "/home/victor/projects/dege-fm/data/sciplex/drugs_train_list.txt"
  sciplex_drugs_test: "/home/victor/projects/dege-fm/data/sciplex/drugs_validation_list.txt"
  seed: 1702
