model_params:
  cell_embedding_dim: 1280
  output_dim: 1280
  condition_dim: 256
  hidden_dims: [2560, 1280, 1280]

train_params:
  num_epochs: 2
  batch_size: 64

dataset_params:
  train_adata_path: "C:\\Users\\curea\\Documents\\bioFM for drug discovery\\dege-fm\\data\\adata_train_v1.h5ad"
  test_adata_path: "C:\\Users\\curea\\Documents\\bioFM for drug discovery\\dege-fm\\data\\adata_test_v1.h5ad"
  seed: 1702
