model_params:
  control_dim: 1280
  drug_emb_dim: 256
  hidden_dims_modulator: [2048, 2048]
  block_hidden_dim: 1280
  num_blocks: 4
  output_dim: 1280
  dropout_rate: 0.1

train_params:
  num_epochs: 3
  batch_size: 512
  lr: 0.0001
  weight_decay: 0.001

dataset_params:
  sciplex_adata_path: "/home/victor/projects/dege-fm/data/sciplex/sciplex_preprocessed.h5ad"
  zhao_adata_path: "/home/victor/projects/dege-fm/data/zhao/zhao_preprocessed.h5ad"
  sciplex_drugs_train: "/home/victor/projects/dege-fm/data/sciplex/drugs_train_list.txt"
  sciplex_drugs_test: "/home/victor/projects/dege-fm/data/sciplex/drugs_validation_list.txt"
  seed: 1702